### ISSUE TITLE
Error occurs when I install pygicp using Python3... (ImportError)

### ISSUE THREAD

**Issue by hyxhope** [SMRT-AIST/fast_gicp#66]
Your C++ code compiles without any error! All ok!
Then when i install pygicp, no error again.  

creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.8/libfast_gicp.so -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.8/pygicp.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for pygicp.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/pygicp.py to pygicp.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pygicp.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygicp.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygicp.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygicp.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygicp.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/pygicp-0.0.1-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pygicp-0.0.1-py3.8-linux-x86_64.egg
creating /home/hyx/miniconda3/envs/slam/lib/python3.8/site-packages/pygicp-0.0.1-py3.8-linux-x86_64.egg
Extracting pygicp-0.0.1-py3.8-linux-x86_64.egg to /home/hyx/miniconda3/envs/slam/lib/python3.8/site-packages
Adding pygicp 0.0.1 to easy-install.pth file

Installed /home/hyx/miniconda3/envs/slam/lib/python3.8/site-packages/pygicp-0.0.1-py3.8-linux-x86_64.egg
Processing dependencies for pygicp==0.0.1
Finished processing dependencies for pygicp==0.0.1

But  when i import pygicp in Python3, error occurs.
>>> import pygicp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_pygicp)

But when i install it using Py2, everything is ok. 
So,
How can I fix this Python3 import error?
Thanks a lot!

**Comment by koide3** [comment]
It seems the package was installed to your python2 environment. Try the following installation command (don't forget "3" after python)

```bash
python3 setup.py install --user
```

**Comment by nightfox0909** [comment]
I had this issue too, seems like pcl introduces a dependency on /usr/bin/python2.7 as mentioned [here](https://github.com/robotology/yarp/issues/2725) and [here](https://issueexplorer.com/issue/robotology/yarp/2725). To check if this is what is causing your issues, take a look at the build/temp./Cmakefiles/pygicp.dir/flags.make, you should find -I /usr/bin/python2.7 . As a temporary workaround, two approaches worked for me
1. renaming /usr/bin/python2.7 to something else, installing the package with setup.py as mentioned above and then renaming the folder back to python2.7. This is hacky, but the easiest workaround for the issue. 
2. A slightly better but still hacky way is to use regexes to filter out python2.7 in the cmakelists file from PCL_INCLUDE_DIRS and the INCLUDE_DIRS for pygicp and fast_gicp.

**Comment by HViktorTsoi** [comment]
> 

Approache 1 worked, but it should be renaming `/usr/include/python2.7` to somewhere else, rahter than ~~/usr/bin/python2.7~~

**Comment by lichengqi0805** [comment]
> I had this issue too, seems like pcl introduces a dependency on /usr/bin/python2.7 as mentioned [here](https://github.com/robotology/yarp/issues/2725) and [here](https://issueexplorer.com/issue/robotology/yarp/2725). To check if this is what is causing your issues, take a look at the build/temp./Cmakefiles/pygicp.dir/flags.make, you should find -I /usr/bin/python2.7 . As a temporary workaround, two approaches worked for me
> 
> 1. renaming /usr/bin/python2.7 to something else, installing the package with setup.py as mentioned above and then renaming the folder back to python2.7. This is hacky, but the easiest workaround for the issue.
> 2. A slightly better but still hacky way is to use regexes to filter out python2.7 in the cmakelists file from PCL_INCLUDE_DIRS and the INCLUDE_DIRS for pygicp and fast_gicp.

This is not working for me.

import pygicp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_pygicp)

**Comment by AndreejS** [comment]
> Approache 1 worked, but it should be renaming /usr/include/python2.7 to somewhere else, rahter than ~~/usr/bin/python2.7~~

I can confirm this was also the case for me. 
However, it seems to depend only on what is used in build/temp./Cmakefiles/pygicp.dir/flags.make, so i'd suggest to verify which path is used there and rename that one.
